# Generated by Django 5.1.1 on 2024-09-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='players',
            field=models.IntegerField(default=0),
        ),
    ]
