# Generated by Django 4.2.10 on 2024-08-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_remove_user_info_full_name_user_info_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='image_url',
        ),
        migrations.AddField(
            model_name='user_info',
            name='imageProfile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
    ]
