# Generated by Django 4.2.10 on 2024-09-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_user_info_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
