# Generated by Django 3.2.5 on 2024-09-25 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0006_user_info_online_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_oauth_user_info_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
