# Generated by Django 4.2.10 on 2024-10-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0008_alter_user_info_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
