# Generated by Django 4.2.10 on 2024-10-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermangement', '0002_matchhistoric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistoric',
            name='create_at',
            field=models.CharField(max_length=20),
        ),
    ]
