# Generated by Django 4.2.10 on 2024-11-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermangement', '0004_matchhistoric_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchhistoric',
            name='create_at',
        ),
    ]
